# fly.toml file generated for overly-complicated-botgame on 2022-10-01T11:14:57+01:00

app = "overly-complicated-botgame"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[experimental]
  auto_rollback = true
